### ISSUE TITLE
Uncaught NOT_FOUND_ERR: NOT_FOUND_ERR: DOMException 8

### ISSUE THREAD

**Issue by AnvarPK** [tim-evans/ember-plupload#56]
Uncaught NOT_FOUND_ERR: NOT_FOUND_ERR: DOMException 8

**Comment by tim-evans** [comment]
Hi @AnvarPK, this isn't really helpful. Could you provide a full stacktrace, or show what your template looks like?

**Comment by mk-conn** [comment]
here is a stack trace, hope this helps:

´´´
DEBUG: -------------------------------
DEBUG: Ember      : 2.3.0
DEBUG: Ember Data : 2.3.3
DEBUG: jQuery     : 2.1.4
DEBUG: -------------------------------

FileInput (moxie.js:3319)
(anonymous function) (plupload.dev.js:1041)
callNext (moxie.js:247)
inSeries (moxie.js:253)
initControls (plupload.dev.js:1135)
plupload.extend.init (plupload.dev.js:1749)
configure (upload-queue.js:76)
findOrCreate (uploader.js:61)
attachUploader (pl-uploader.js:133)
Queue.invoke (ember.debug.js:327)
Queue.flush (ember.debug.js:391)
DeferredActionQueues.flush (ember.debug.js:192)
Backburner.end (ember.debug.js:570)
Backburner.run (ember.debug.js:692)
Backburner.join (ember.debug.js:712)
run.join (ember.debug.js:20631)
_emberMetalAssign.default.handleEvent (ember.debug.js:45688)
exports.default._emberMetalMixin.Mixin.create._Mixin$create.handleEvent (ember.debug.js:42630)
exports.default._emberRuntimeSystemObject.default.extend._bubbleEvent (ember.debug.js:43712)
(anonymous function) (ember.debug.js:43654)
jQuery.event.dispatch (jquery.js:4435)
elemData.handle (jquery.js:4121)
´´´

Seems to happen since ember 2.3.0 - didn't have this error before...

**Comment by mk-conn** [comment]
Thats the piece of code that throws the exception... 
```
browseButton = Dom.get(options.browse_button);
if (!browseButton) {
// browse button is required
throw new x.DOMException(x.DOMException.NOT_FOUND_ERR);
}
```

Weird...

**Comment by tim-evans** [comment]
@mk-conn Thanks for the update. I assume that it's the same problem. I think the best way to fix this is to throw an error early on that lets developers know that they don't have a browse button available.

**Comment by tim-evans** [comment]
The [newest release](https://github.com/tim-evans/ember-plupload/blob/master/CHANGELOG.md#11312-february-5-2016) should make this easier to debug. Let me know if this is still an issue.
